name: Export issues
on:
  issues:
    types: [closed]
  workflow_dispatch:
env: 
  fundR: ${{ fromJSON(github.event.issue.body).fund }}
  GitB: "cardano-ambassadors"
 # schedule:
    # run every 8 hours
  #  - cron:  '0 0,8,16 * * *'
jobs:
  issue:
    runs-on: ubuntu-latest
    name: discord
    steps:
 #    - name: Set env fun
 #      run: |
 #         if [[ $fundR == 'Fund8' ]]; then
 #             echo "fun=F8" >> "$GITHUB_ENV"
 #         else 
 #             echo "fun=F6" >> "$GITHUB_ENV"
 #         fi
     - name: Fund 6
       if: ${{ env.fundR == 'Fund6' }}
       run: echo "fun=F6" >> "$GITHUB_ENV"
     - name: Fund 7
       if: ${{ env.fundR == 'Fund7' }}
       run: echo "fun=F7" >> "$GITHUB_ENV"
     - name: Fund 8
       if: ${{ env.fundR == 'Fund8' }}
       run: echo "fun=F8" >> "$GITHUB_ENV"
       
     - name: Set env data
       id: propdata
       run: |
         echo "::set-output name=data::$(curl -s https://raw.githubusercontent.com/treasuryguild/treasury-v3/main/proposals/${{ env.fun }}-${{ fromJSON(github.event.issue.body).proposal }}.json | jq '.wallet' | sed 's/\"//g')"
     - name: Set env wallet
       run: |
         echo "wallet=${{ steps.propdata.outputs.data }}" >> "$GITHUB_ENV"
     - name: Test Custom3
       if: ${{ contains(github.event.issue.labels.*.name, 'Incoming') }}
       uses: rjstone/discord-webhook-notify@v1
       with:
         severity: info
         username: Treasury Guild
         color: '#03fc2c'
         avatarUrl: https://github.com/treasuryguild/Treasury-Guild/raw/main/logo132.png
         description: |
           `${{ fromJSON(github.event.issue.body).project }} | ${{ fromJSON(github.event.issue.body).fund }} |` [Ideascale](${{ fromJSON(github.event.issue.body).ideascale }})
         details: | 
           `${{ fromJSON(github.event.issue.body).proposal }} | ${{ fromJSON(github.event.issue.body).budget }}`
           ```fix
           ${{ fromJSON(github.event.issue.body).description }}
           ```
           `Amount Received` - [CardanoScan](https://cardanoscan.io/transaction/${{ fromJSON(github.event.issue.body).txid }}) - [GitBook](https://treasury-guild.gitbook.io/${{ env.GitB }}/)
           ```md
           * ADA - ${{ fromJSON(github.event.issue.body).ada }} 
           ```
           `Wallet Balance of` [${{ fromJSON(github.event.issue.body).proposal }}](https://pool.pm/${{ env.wallet }})
           ```css
           ${{ fromJSON(github.event.issue.body).wallet-balance[0] }} ${{ fromJSON(github.event.issue.body).wallet-balance[1] }} ${{ fromJSON(github.event.issue.body).wallet-balance[2] }}
           ```    
         footer: Exchange Rate - ${{ fromJSON(github.event.issue.body).exchange-rate }}
         text: ${{ github.event.issue.title }}
         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
     - name: Test Custom4
       if: ${{ contains(github.event.issue.labels.*.name, 'Outgoing') }}
       uses: rjstone/discord-webhook-notify@v1
       with:
         severity: info
         username: Treasury Guild
         color: '#ff00aa'
         avatarUrl: https://github.com/treasuryguild/Treasury-Guild/raw/main/logo132.png
         description: |
           `${{ fromJSON(github.event.issue.body).project }} | ${{ fromJSON(github.event.issue.body).fund }} |` [Ideascale](${{ fromJSON(github.event.issue.body).ideascale }})
         details: | 
           `${{ fromJSON(github.event.issue.body).proposal }} | ${{ fromJSON(github.event.issue.body).budget }}`
           ```fix
           ${{ fromJSON(github.event.issue.body).description }}
           ```
           `Amount Paid` - [CardanoScan](https://cardanoscan.io/transaction/${{ fromJSON(github.event.issue.body).txid }}) - [GitBook](https://treasury-guild.gitbook.io/${{ env.GitB }}/)
           ```md
           * ADA - ${{ fromJSON(github.event.issue.body).ada }} 
           ```
           `Wallet Balance of` [${{ fromJSON(github.event.issue.body).proposal }}](https://pool.pm/${{ env.wallet }})
           ```css
           ${{ fromJSON(github.event.issue.body).wallet-balance[0] }} ${{ fromJSON(github.event.issue.body).wallet-balance[1] }} ${{ fromJSON(github.event.issue.body).wallet-balance[2] }}
           ```    
         footer: Exchange Rate - ${{ fromJSON(github.event.issue.body).exchange-rate }}
         text: ${{ github.event.issue.title }}
         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
 # schedule:
    # run every 8 hours
  #  - cron:  '0 0,8,16 * * *'
#jobs:
#  issue:
#    runs-on: ubuntu-latest
#    name: discord
#    steps:
#     - name: Test Custom
#       uses: rjstone/discord-webhook-notify@v1
#       with:
#         severity: info
#         username: Treasury Guild
#         color: '#ff00aa'
#         avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
#         description: "Payment Notification"
#         details: ${{ github.event.issue.body }} https://treasury-guild.gitbook.io/cardano-ambassadors/
#         footer: "View transaction in Gitbook link"
#         text: ${{ github.event.issue.title }}
#         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
